<a href="https://colab.research.google.com/github/mehedihasan-cse/Data-Analysis-with-Pandas/blob/main/Filter_Text_from_Facebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import pandas as pd

In [77]:
df = pd.read_csv('/content/ESUIT _ Comments Exporter for Facebook™ (125).csv')

In [78]:
df.head(2)

,Id,UserId,Avatar,Author,Content,Url,ReactionsCount,Depth,SubCommentsCount,CommentAt
0,Y29tbWVudDo5MTk2MTMxNTM1MjYxMjBfMzc3NjQwNjI4Mj...,100064323325846,https://scontent.fdac45-1.fna.fbcdn.net/v/t39....,Joshim's Tutorial,পরিবর্তন কেউ এসে করে দিবে না; পরিবর্তনটা আগে ন...,https://www.facebook.com/joshimsir/posts/pfbid...,18,0,2,08/18/2024 10:08:25 PM
1,Y29tbWVudDo5MTk2MTMxNTM1MjYxMjBfNTIxMDE1NTkzNz...,100088367672463,https://scontent.fdac45-1.fna.fbcdn.net/v/t39....,Abdul WOhab Khondkar,আগে আমাদের নিজেদের বদলাতে হবে দেশ এমনিতেই বদলে...,https://www.facebook.com/joshimsir/posts/pfbid...,3,0,0,08/19/2024 01:18:43 AM

In [79]:
df.columns

Index(['Id', 'UserId', 'Avatar', 'Author', 'Content', 'Url', 'ReactionsCount',
       'Depth', 'SubCommentsCount', 'CommentAt'],
      dtype='object')

In [80]:
df = df.drop(columns = ['Id', 'UserId', 'Avatar', 'Author', 'Url', 'ReactionsCount',
       'Depth', 'SubCommentsCount', 'CommentAt'])
df

                                               Content
0    পরিবর্তন কেউ এসে করে দিবে না; পরিবর্তনটা আগে ন...
1    আগে আমাদের নিজেদের বদলাতে হবে দেশ এমনিতেই বদলে...
2    আমি মনে করি ভালো একজন শাসক পেতে হলে আগে জনগন আ...
3         স্মৃতির পাতায় আজও রয়ে গেছে এই ফুট ওভার ব্রিজ
4                                নিজে বালো তো জগত বালো
..                                                 ...
120  Kalk Dhaka  teke aslam sob ager motoi...deklam..😊
121               এই জায়গায় সারা জীবন এভাবেই দেখে আসছি
122                         ইনশাআল্লাহ সফল দেশের মানুষ
123  সবার আগে নিজেকে পরিবর্তন করতে হবে। আসুন আমরা ন...
124                                         মাশাআল্লাহ

[125 rows x 1 columns]

In [81]:
df

                                               Content
0    পরিবর্তন কেউ এসে করে দিবে না; পরিবর্তনটা আগে ন...
1    আগে আমাদের নিজেদের বদলাতে হবে দেশ এমনিতেই বদলে...
2    আমি মনে করি ভালো একজন শাসক পেতে হলে আগে জনগন আ...
3         স্মৃতির পাতায় আজও রয়ে গেছে এই ফুট ওভার ব্রিজ
4                                নিজে বালো তো জগত বালো
..                                                 ...
120  Kalk Dhaka  teke aslam sob ager motoi...deklam..😊
121               এই জায়গায় সারা জীবন এভাবেই দেখে আসছি
122                         ইনশাআল্লাহ সফল দেশের মানুষ
123  সবার আগে নিজেকে পরিবর্তন করতে হবে। আসুন আমরা ন...
124                                         মাশাআল্লাহ

[125 rows x 1 columns]

In [82]:
df.isna().sum()

Content    0
dtype: int64

In [83]:
import re

def has_english(row):
    # Check if the 'Content' column contains any English letters
    return bool(re.search(r'[a-zA-Z]', row['Content']))

# Filter the DataFrame to keep only rows without English letters
df = df[~df.apply(has_english, axis=1)]

print(df)

                                               Content
0    পরিবর্তন কেউ এসে করে দিবে না; পরিবর্তনটা আগে ন...
1    আগে আমাদের নিজেদের বদলাতে হবে দেশ এমনিতেই বদলে...
2    আমি মনে করি ভালো একজন শাসক পেতে হলে আগে জনগন আ...
3         স্মৃতির পাতায় আজও রয়ে গেছে এই ফুট ওভার ব্রিজ
4                                নিজে বালো তো জগত বালো
..                                                 ...
119                                    বাহ বাংলাদেশ ❤️
121               এই জায়গায় সারা জীবন এভাবেই দেখে আসছি
122                         ইনশাআল্লাহ সফল দেশের মানুষ
123  সবার আগে নিজেকে পরিবর্তন করতে হবে। আসুন আমরা ন...
124                                         মাশাআল্লাহ

[82 rows x 1 columns]

In [84]:
df.isna().sum()

Content    0
dtype: int64

In [85]:
df.reset_index(drop=True, inplace=True)

In [86]:
df

                                              Content
0   পরিবর্তন কেউ এসে করে দিবে না; পরিবর্তনটা আগে ন...
1   আগে আমাদের নিজেদের বদলাতে হবে দেশ এমনিতেই বদলে...
2   আমি মনে করি ভালো একজন শাসক পেতে হলে আগে জনগন আ...
3        স্মৃতির পাতায় আজও রয়ে গেছে এই ফুট ওভার ব্রিজ
4                               নিজে বালো তো জগত বালো
..                                                ...
77                                    বাহ বাংলাদেশ ❤️
78               এই জায়গায় সারা জীবন এভাবেই দেখে আসছি
79                         ইনশাআল্লাহ সফল দেশের মানুষ
80  সবার আগে নিজেকে পরিবর্তন করতে হবে। আসুন আমরা ন...
81                                         মাশাআল্লাহ

[82 rows x 1 columns]

In [89]:
df.download('Content')